
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Entry txt_cog;
	private global::Gtk.Label lbl_cog;
	private global::Gtk.Entry txt_nome;
	private global::Gtk.Label lbl_nome;
	private global::Gtk.Entry txt_clas;
	private global::Gtk.Label lbl_clas;
	private global::Gtk.Label lbl_ind;
	private global::Gtk.Entry txt_Ind;
	private global::Gtk.Button btn_1;
	private global::Gtk.Entry txt_num;
	private global::Gtk.Label lbl_num;
	private global::Gtk.Button btn_2;
	private global::Gtk.Button btn_3;
	private global::Gtk.Arrow arrow3;
	private global::Gtk.Arrow arrow2;
	private global::Gtk.Arrow arrow1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView stamp;
	private global::Gtk.Entry txt_file;
	private global::Gtk.Label lbl_file;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txt_cog = new global::Gtk.Entry ();
		this.txt_cog.WidthRequest = 110;
		this.txt_cog.CanFocus = true;
		this.txt_cog.Name = "txt_cog";
		this.txt_cog.IsEditable = true;
		this.txt_cog.InvisibleChar = '●';
		this.fixed1.Add (this.txt_cog);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txt_cog]));
		w1.X = 30;
		w1.Y = 35;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbl_cog = new global::Gtk.Label ();
		this.lbl_cog.Name = "lbl_cog";
		this.lbl_cog.LabelProp = global::Mono.Unix.Catalog.GetString ("Inserisci cognome");
		this.fixed1.Add (this.lbl_cog);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lbl_cog]));
		w2.X = 28;
		w2.Y = 15;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txt_nome = new global::Gtk.Entry ();
		this.txt_nome.WidthRequest = 110;
		this.txt_nome.CanFocus = true;
		this.txt_nome.Name = "txt_nome";
		this.txt_nome.IsEditable = true;
		this.txt_nome.InvisibleChar = '●';
		this.fixed1.Add (this.txt_nome);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txt_nome]));
		w3.X = 150;
		w3.Y = 35;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbl_nome = new global::Gtk.Label ();
		this.lbl_nome.Name = "lbl_nome";
		this.lbl_nome.LabelProp = global::Mono.Unix.Catalog.GetString ("Inserisci nome");
		this.fixed1.Add (this.lbl_nome);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lbl_nome]));
		w4.X = 158;
		w4.Y = 15;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txt_clas = new global::Gtk.Entry ();
		this.txt_clas.WidthRequest = 100;
		this.txt_clas.CanFocus = true;
		this.txt_clas.Name = "txt_clas";
		this.txt_clas.IsEditable = true;
		this.txt_clas.InvisibleChar = '●';
		this.fixed1.Add (this.txt_clas);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txt_clas]));
		w5.X = 400;
		w5.Y = 35;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbl_clas = new global::Gtk.Label ();
		this.lbl_clas.Name = "lbl_clas";
		this.lbl_clas.LabelProp = global::Mono.Unix.Catalog.GetString ("Inserisci classe");
		this.fixed1.Add (this.lbl_clas);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lbl_clas]));
		w6.X = 402;
		w6.Y = 15;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbl_ind = new global::Gtk.Label ();
		this.lbl_ind.Name = "lbl_ind";
		this.lbl_ind.LabelProp = global::Mono.Unix.Catalog.GetString ("Inserisci Indirizzo");
		this.fixed1.Add (this.lbl_ind);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lbl_ind]));
		w7.X = 510;
		w7.Y = 15;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txt_Ind = new global::Gtk.Entry ();
		this.txt_Ind.WidthRequest = 100;
		this.txt_Ind.CanFocus = true;
		this.txt_Ind.Name = "txt_Ind";
		this.txt_Ind.IsEditable = true;
		this.txt_Ind.InvisibleChar = '●';
		this.fixed1.Add (this.txt_Ind);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txt_Ind]));
		w8.X = 510;
		w8.Y = 35;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn_1 = new global::Gtk.Button ();
		this.btn_1.CanFocus = true;
		this.btn_1.Name = "btn_1";
		this.btn_1.UseUnderline = true;
		this.btn_1.Label = global::Mono.Unix.Catalog.GetString ("Salva in memoria");
		this.fixed1.Add (this.btn_1);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btn_1]));
		w9.X = 60;
		w9.Y = 170;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txt_num = new global::Gtk.Entry ();
		this.txt_num.WidthRequest = 110;
		this.txt_num.CanFocus = true;
		this.txt_num.Name = "txt_num";
		this.txt_num.IsEditable = true;
		this.txt_num.InvisibleChar = '●';
		this.fixed1.Add (this.txt_num);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txt_num]));
		w10.X = 275;
		w10.Y = 35;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbl_num = new global::Gtk.Label ();
		this.lbl_num.Name = "lbl_num";
		this.lbl_num.LabelProp = global::Mono.Unix.Catalog.GetString ("Inserisci numero");
		this.fixed1.Add (this.lbl_num);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lbl_num]));
		w11.X = 278;
		w11.Y = 15;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn_2 = new global::Gtk.Button ();
		this.btn_2.CanFocus = true;
		this.btn_2.Name = "btn_2";
		this.btn_2.UseUnderline = true;
		this.btn_2.Label = global::Mono.Unix.Catalog.GetString ("Salva su file");
		this.fixed1.Add (this.btn_2);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btn_2]));
		w12.X = 60;
		w12.Y = 205;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn_3 = new global::Gtk.Button ();
		this.btn_3.CanFocus = true;
		this.btn_3.Name = "btn_3";
		this.btn_3.UseUnderline = true;
		this.btn_3.Label = global::Mono.Unix.Catalog.GetString ("Stampa da file");
		this.fixed1.Add (this.btn_3);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btn_3]));
		w13.X = 60;
		w13.Y = 240;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.arrow3 = new global::Gtk.Arrow (((global::Gtk.ArrowType)(3)), ((global::Gtk.ShadowType)(2)));
		this.arrow3.Name = "arrow3";
		this.fixed1.Add (this.arrow3);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.arrow3]));
		w14.X = 36;
		w14.Y = 245;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.arrow2 = new global::Gtk.Arrow (((global::Gtk.ArrowType)(3)), ((global::Gtk.ShadowType)(2)));
		this.arrow2.Name = "arrow2";
		this.fixed1.Add (this.arrow2);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.arrow2]));
		w15.X = 36;
		w15.Y = 175;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.arrow1 = new global::Gtk.Arrow (((global::Gtk.ArrowType)(3)), ((global::Gtk.ShadowType)(2)));
		this.arrow1.Name = "arrow1";
		this.fixed1.Add (this.arrow1);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.arrow1]));
		w16.X = 36;
		w16.Y = 210;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.WidthRequest = 385;
		this.GtkScrolledWindow.HeightRequest = 150;
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.stamp = new global::Gtk.TextView ();
		this.stamp.WidthRequest = 300;
		this.stamp.HeightRequest = 100;
		this.stamp.CanFocus = true;
		this.stamp.Name = "stamp";
		this.GtkScrolledWindow.Add (this.stamp);
		this.fixed1.Add (this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow]));
		w18.X = 227;
		w18.Y = 146;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txt_file = new global::Gtk.Entry ();
		this.txt_file.CanFocus = true;
		this.txt_file.Name = "txt_file";
		this.txt_file.IsEditable = true;
		this.txt_file.InvisibleChar = '●';
		this.fixed1.Add (this.txt_file);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txt_file]));
		w19.X = 255;
		w19.Y = 100;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbl_file = new global::Gtk.Label ();
		this.lbl_file.Name = "lbl_file";
		this.lbl_file.LabelProp = global::Mono.Unix.Catalog.GetString ("Inserisci il nome del file");
		this.fixed1.Add (this.lbl_file);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lbl_file]));
		w20.X = 260;
		w20.Y = 77;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 629;
		this.DefaultHeight = 310;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btn_1.Clicked += new global::System.EventHandler (this.OnBtn1Clicked);
		this.btn_2.Clicked += new global::System.EventHandler (this.OnBtn2Clicked);
		this.btn_3.Clicked += new global::System.EventHandler (this.OnBtn3Clicked);
	}
}
